export const GET_ERRORS_ADDRESS = 'GET_ERRORS_ADDRESS';
export const GET_ERRORS_BANK_DETAILS = 'GET_ERRORS_BANK_DETAILS';
export const TEST_DISPATCH = 'TEST_DISPATCH';
export const GET_ADDRESS = 'GET_ADDRESS';
export const GET_BANKDETAILS = 'GET_BANKDETAILS';
export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const GET_ERROTS_SUPPLIER = 'GET_ERROTS_SUPPLIER';
export const GET_ALL_SUPPLIERS = 'GET_ALL_SUPPLIERS';
